# Form implementation generated from reading ui file 'AgeCalc.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from datetime import date
from dateutil.relativedelta import relativedelta


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit_DBD = QtWidgets.QLineEdit(Form)
        self.lineEdit_DBD.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_DBD.setObjectName("lineEdit_DBD")
        self.horizontalLayout.addWidget(self.lineEdit_DBD)
        self.lineEdit_DBM = QtWidgets.QLineEdit(Form)
        self.lineEdit_DBM.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_DBM.setObjectName("lineEdit_DBM")
        self.horizontalLayout.addWidget(self.lineEdit_DBM)
        self.lineEdit_DBY = QtWidgets.QLineEdit(Form)
        self.lineEdit_DBY.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_DBY.setObjectName("lineEdit_DBY")
        self.horizontalLayout.addWidget(self.lineEdit_DBY)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEdit_DTD_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_DTD_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_DTD_2.setObjectName("lineEdit_DTD_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_DTD_2)
        self.lineEdit_DTM_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_DTM_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_DTM_2.setObjectName("lineEdit_DTM_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_DTM_2)
        self.lineEdit_DTY_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_DTY_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_DTY_2.setObjectName("lineEdit_DTY_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_DTY_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.get_result)
        self.verticalLayout.addWidget(self.pushButton)
        self.age_day = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.age_day.setFont(font)
        self.age_day.setStyleSheet("QLabel {\n"
"\n"
"color:green\n"
"\n"
"}")
        self.age_day.setText("")
        self.age_day.setObjectName("age_day")
        self.verticalLayout.addWidget(self.age_day)
        self.age_dmy = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.age_dmy.setFont(font)
        self.age_dmy.setStyleSheet("QLabel {\n"
"\n"
"color:green\n"
"\n"
"}")
        self.age_dmy.setText("")
        self.age_dmy.setObjectName("age_dmy")
        self.verticalLayout.addWidget(self.age_dmy)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def get_result(self):
        birth_date = int(self.lineEdit_DBD.text())
        birth_month = int(self.lineEdit_DBM.text())
        birth_year = int(self.lineEdit_DBY.text())

        today_date = int(self.lineEdit_DTD_2.text())
        today_month = int(self.lineEdit_DTM_2.text())
        today_year = int(self.lineEdit_DTY_2.text())

        date_birth = date(birth_year, birth_month, birth_date)
        date_today = date(today_year, today_month, today_date)

        age_in_days = (date_today - date_birth).days

        text1 = 'Your Age in days: %d days.' % age_in_days

        self.age_day.setText(str(text1))

        rdelta = relativedelta(date_today, date_birth)

        text2 = "Your Age: %d years %d months %d days." %(rdelta.years, rdelta.months, rdelta.days)

        self.age_dmy.setText(str(text2))


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AgeCalc"))
        self.label.setText(_translate("Form", "Calculate Your Age"))
        self.label_2.setText(_translate("Form", "Date Of Birth:"))
        self.lineEdit_DBD.setPlaceholderText(_translate("Form", "Date"))
        self.lineEdit_DBM.setPlaceholderText(_translate("Form", "Month"))
        self.lineEdit_DBY.setPlaceholderText(_translate("Form", "Year"))
        self.label_3.setText(_translate("Form", "Date Today:"))
        self.lineEdit_DTD_2.setPlaceholderText(_translate("Form", "Date"))
        self.lineEdit_DTM_2.setPlaceholderText(_translate("Form", "Month"))
        self.lineEdit_DTY_2.setPlaceholderText(_translate("Form", "Year"))
        self.pushButton.setText(_translate("Form", "Show Age"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
